version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./logmate
      dockerfile: Dockerfile.backend
    container_name: django_backend
    command: daphne -b 0.0.0.0 -p 8000 logmate.asgi:application
    volumes:
      - ./logmate:/app
      - shared_tmp:/tmp
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=logmate.settings
      - REDIS_URL=redis://redis:6379/0

  worker:
    build:
      context: ./logmate
      dockerfile: Dockerfile.backend
    container_name: celery_worker
    command: celery -A logmate worker --loglevel=info --concurrency=4
    volumes:
      - ./logmate:/app
      - shared_tmp:/tmp
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_URL=redis://redis:6379/0
      
  frontend:
    build:
      context: ./logmate_frontend
      dockerfile: Dockerfile.frontend
    container_name: react_frontend
    volumes:
      - ./logmate_frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this in production!
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

volumes:
  shared_tmp:
  grafana_data:
  prometheus_data: