services:
  - name: redis
    type: redis
    plan: free
    ipAllowList: []  # Allows access from all Render services

  - name: django-backend
    type: web
    env: docker
    dockerfilePath: ./logmate/Dockerfile.backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: logmate.settings
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
    autoDeploy: true

  - name: celery-worker
    type: worker
    env: docker
    dockerfilePath: ./logmate/Dockerfile.backend
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
    autoDeploy: true

  - name: react-frontend
    type: web
    env: docker
    dockerfilePath: ./logmate_frontend/Dockerfile.frontend
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://django-backend.onrender.com
    autoDeploy: true
